version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    hostname: localhost
    volumes:
      - "./inc/default.conf:/etc/nginx/conf.d/default.conf"
      - "./openrsc_web:/var/www/html/openrsc_web"
      - "./log:/var/log/nginx"
      - "./avatars:/var/www/html/openrsc_web/public/img/avatars"
      - "./board:/var/www/html/openrsc_web/public/board"
      - "./sql:/var/www/html/openrsc_web/public/sql"
      - "./downloads:/var/www/html/openrsc_web/public/downloads"
      - "./cache:/var/www/html/openrsc_web/public/cache"

  php:
    image: openrsc/php-laravel:latest
    container_name: php
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "./inc/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./openrsc_web:/var/www/html/openrsc_web"
      - "./board:/var/www/html/openrsc_web/public/board"
      - "./sql:/var/www/html/openrsc_web/public/sql"
      - "./downloads:/var/www/html/openrsc_web/public/downloads"
