version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./etc/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./etc/nginx/log:/var/log/nginx
      - ./downloads:/var/www/html/site/public/downloads
      - ./wiki/images:/var/www/html/images
      - ./site/public/stylesheets:/var/www/html/site/public/stylesheets
      - ./site/public/images:/var/www/html/site/public/images

  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    restart: always
    ports:
      - "127.0.0.1:9000:80"
    volumes:
      - ./etc/wiki/LocalSettings.php:/var/www/html/LocalSettings.php # MediaWiki config located in etc
      - ./wiki/images:/var/www/html/images

  node:
    image: node:latest
    container_name: node
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    command: bash -c "cd /var/www/html/site && npm start"
    volumes:
      - ./site:/var/www/html/site

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - HIDE_PHP_VERSION=true
      - UPLOAD_LIMIT=10485760
      - PMA_ARBITRARY=1
    ports:
      - "4000:80"
    volumes:
      - ./etc/nginx/phpmyadmin/config.inc.php:/var/www/html/config.inc.php # PHPMyAdmin config located in etc

networks:
  default:
    external:
      name: database
