version: '3'
services:

  nginx:
    hostname: ${HOSTNAME}
    environment:
      VIRTUAL_HOST: ${HOSTNAME},${HOSTNAME2},${HOSTNAME3},${HOSTNAME4}
      LETSENCRYPT_HOST: ${HOSTNAME},${HOSTNAME2},${HOSTNAME3},${HOSTNAME4}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NGINX_HOST: ${HOSTNAME}
    expose:
      - 80
      - 443
    volumes:
      - "./inc/default.conf:/etc/nginx/conf.d/default.conf"
      - "./openrsc_web:/var/www/html/openrsc_web"
      - "/var/log/nginx:/var/log/nginx"
      - "/opt/Game/server/avatars:/var/www/html/avatars"

  php:
    environment:
      - XDEBUG=false

networks:
  default:
    external:
      name: nginx-proxy
