version: '3'
services:

  nginx:
    hostname: ${HOSTNAME}
    environment:
      VIRTUAL_HOST: ${HOSTNAME},${HOSTNAME2},${HOSTNAME3},${HOSTNAME4},${HOSTNAME5}
      LETSENCRYPT_HOST: ${HOSTNAME},${HOSTNAME2},${HOSTNAME3},${HOSTNAME4},${HOSTNAME5}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NGINX_HOST: ${HOSTNAME}
    expose:
      - 80
      - 443
    volumes:
      - "./inc/default.conf:/etc/nginx/conf.d/default.conf"
      - "./openrsc_web:/var/www/html/openrsc_web"
      - "/var/log/nginx:/var/log/nginx"
      - "./avatars:/var/www/html/openrsc_web/public/img/avatars"
      - "./board:/var/www/html/openrsc_web/public/board"
      - "./sql:/var/www/html/openrsc_web/public/sql"
      - "./downloads:/var/www/html/openrsc_web/public/downloads"
      - "./cache:/var/www/html/openrsc_web/public/cache"

  php:
    environment:
      - XDEBUG=false

networks:
  default:
    external:
      name: nginx-proxy
